import { describe, expect, it } from "vitest";
import {
  createCircuitContext,
  createConstructorContext,
  type CircuitContext,
} from "@midnight-ntwrk/compact-runtime";
import {
  Contract,
  DisputeKind,
  Phase,
  ledger,
  pureCircuits,
  type Witnesses,
} from "../contract/managed/parity/contract/index.js";
import { witnesses, type PrivateState } from "../src/contract/witnesses";
import { encodeLabel, fromHex, toHex } from "../src/lib/bytes";
import { buildCategory, figures, inclusionProof, rootFromRecord, type Entry } from "../src/lib/payroll";

// These tests run the circuits generated by compactc 0.31.1 through the Compact
// runtime. Every rejection is an assert inside a circuit, so it is part of the
// proof and cannot be skipped by a modified client.

const bytes = (n: number) => new Uint8Array(32).fill(n);
const hr = bytes(1);
const period = encodeLabel("2026");
const alice = bytes(10);
const bea = bytes(11);
const mallory = bytes(66);
const coinKey = "00".repeat(32);

const people = (women: number[], men: number[]): Entry[] => [
  ...women.map((pay, i) => ({ employee: `w${i}`, woman: true, pay })),
  ...men.map((pay, i) => ({ employee: `m${i}`, woman: false, pay })),
];
const engineering = buildCategory("Engineering", people([5100, 5200, 5000, 5150, 5250, 5140], [5600, 5700, 5500, 5650, 5550, 5620, 5610]));
const drivers = buildCategory("Drivers", people([3000, 3100, 2950], [3200, 3150, 3300, 3250, 3180, 3220]));

const batch = (commitments: Uint8Array[]) => [...commitments, ...Array.from({ length: 16 - commitments.length }, () => new Uint8Array(32))];

function setup(custom: Witnesses<PrivateState> = witnesses) {
  const contract = new Contract(custom);
  const organizer: PrivateState = {
    organizerSecret: hr,
    payroll: { [engineering.id]: engineering.records, [drivers.id]: drivers.records },
  };
  const initial = contract.initialState(
    createConstructorContext(organizer, coinKey),
    period,
    pureCircuits.organizerCommitment(hr),
  );
  let context: CircuitContext<PrivateState> = createCircuitContext("01".repeat(32), coinKey, initial.currentContractState, organizer);
  const as = (ps: PrivateState) => (context = { ...context, currentPrivateState: ps });
  const run = <R extends { context: CircuitContext<PrivateState> }>(fn: (c: CircuitContext<PrivateState>) => R): R => {
    const out = fn(context);
    context = out.context;
    return out;
  };
  const c = contract.impureCircuits;
  return {
    get state() {
      return ledger(context.currentQueryContext.state);
    },
    as,
    asHr: () => as(organizer),
    register: (...secrets: Uint8Array[]) =>
      run((x) => c.registerEmployees(x, batch(secrets.map((s) => pureCircuits.credentialCommitment(period, s))))),
    commit: (cat = engineering, root = cat.root) => run((x) => c.commitCategory(x, fromHex(cat.id, 32), fromHex(root, 32))),
    open: () => run((x) => c.openCheckWindow(x)),
    close: () => run((x) => c.closeCheckWindow(x)),
    resolve: (n: Uint8Array) => run((x) => c.resolveDispute(x, n)),
    publish: (cat = engineering) => run((x) => c.publishCategory(x, fromHex(cat.id, 32))),
    dispute: (secret: Uint8Array, kind = DisputeKind.payAmount) => {
      const saved = context.currentPrivateState;
      as({ employeeSecret: secret });
      try {
        return run((x) => c.fileDispute(x, kind));
      } finally {
        as(saved);
      }
    },
  };
}

function checking(custom?: Witnesses<PrivateState>) {
  const app = setup(custom);
  app.register(alice);
  app.register(bea);
  app.commit(engineering);
  app.commit(drivers);
  app.open();
  return app;
}

describe("a proven report", () => {
  it("publishes counts and pay totals computed from exactly the committed records", () => {
    const app = checking();
    app.close();
    app.publish(engineering);
    const result = app.state.results.lookup(fromHex(engineering.id, 32));
    expect(result).toEqual({ women: 6n, men: 7n, womenPay: 30840n, menPay: 39230n });
    const f = figures(result);
    expect(f.womenAverage).toBe(5140);
    expect(f.menAverage).toBeCloseTo(5604.29, 2);
    expect(f.gap).toBeCloseTo(8.28, 2);
  });

  it("withholds a category with fewer than 5 women, disclosing nothing but that decision", () => {
    const app = checking();
    app.close();
    const out = app.publish(drivers);
    const id = fromHex(drivers.id, 32);
    expect(app.state.withheld.member(id)).toBe(true);
    expect(app.state.results.member(id)).toBe(false);
    const transcript = JSON.stringify(out.proofData.publicTranscript, (_, v) =>
      typeof v === "bigint" ? v.toString() : v instanceof Uint8Array ? toHex(v) : v,
    );
    // 3 women and their total pay (9050) never appear.
    expect(transcript).not.toContain("9050");
  });

  it("rejects records that differ from the committed payroll", () => {
    const tampered = engineering.records.map((r, i) => (i === 0 ? { ...r, pay: r.pay + 800n } : r));
    const app = checking({
      ...witnesses,
      categoryRecords: ({ privateState }) => [privateState, tampered],
    });
    app.close();
    expect(() => app.publish(engineering)).toThrow("Records do not match the committed payroll");
  });

  it("refuses to publish a category twice or one that was never committed", () => {
    const app = checking();
    app.close();
    app.publish(engineering);
    expect(() => app.publish(engineering)).toThrow("Category already published");
    const other = buildCategory("Legal", people([1, 2, 3, 4, 5], [1, 2, 3, 4, 5]));
    expect(() => app.publish(other)).toThrow("Category was never committed");
  });
});

describe("anonymous disputes", () => {
  it("records a dispute under a nullifier and blocks proving until it is resolved", () => {
    const app = checking();
    const n = app.dispute(alice).result;
    expect(n).toEqual(pureCircuits.disputeNullifier(period, alice));
    expect(app.state.disputes.lookup(n)).toBe(DisputeKind.payAmount);
    expect(() => app.close()).toThrow("Resolve every open dispute first");
    app.resolve(n);
    expect(app.state.resolvedDisputes).toBe(1n);
    app.close();
    expect(app.state.phase).toBe(Phase.proving);
  });

  it("allows one dispute per employee per report", () => {
    const app = checking();
    app.dispute(alice);
    expect(() => app.dispute(alice, DisputeKind.category)).toThrow("Already disputed this report");
    app.dispute(bea);
    expect(app.state.openDisputes.size()).toBe(2n);
  });

  it("rejects someone who is not a registered employee", () => {
    const app = checking();
    expect(() => app.dispute(mallory)).toThrow("not registered");
  });

  it("rejects a malicious witness that submits another employee's valid path", () => {
    const app = checking({
      ...witnesses,
      credentialPath: ({ ledger, privateState }) => [
        privateState,
        ledger.employees.findPathForLeaf(pureCircuits.credentialCommitment(period, alice))!,
      ],
    });
    expect(() => app.dispute(mallory)).toThrow("Credential path does not match employee");
  });

  it("lets HR correct a disputed category while the window is open", () => {
    const app = checking();
    const n = app.dispute(alice).result;
    const corrected = buildCategory("Engineering", people([5100, 5200, 5000, 5150, 5250, 5140], [5600, 5700, 5500, 5650, 5550, 5620, 5610]));
    app.commit(engineering, corrected.root);
    expect(toHex(app.state.payroll.lookup(fromHex(engineering.id, 32)))).toBe(corrected.root);
    app.resolve(n);
    expect(() => app.resolve(n)).toThrow("No open dispute with this reference");
  });

  it("keeps the employee's secret and credential out of the dispute transcript", () => {
    const app = checking();
    const out = app.dispute(alice);
    const transcript = JSON.stringify(out.proofData.publicTranscript, (_, v) =>
      typeof v === "bigint" ? v.toString() : v instanceof Uint8Array ? toHex(v) : v,
    );
    expect(transcript).toContain(toHex(out.result));
    expect(transcript).not.toContain(toHex(alice));
    expect(transcript).not.toContain(toHex(pureCircuits.credentialCommitment(period, alice)));
  });
});

describe("authorization", () => {
  it("rejects every organizer action from anyone without the organizer secret", () => {
    const app = setup();
    app.as({ organizerSecret: mallory });
    expect(() => app.register(alice)).toThrow("Organizer authorization required");
    expect(() => app.commit()).toThrow("Organizer authorization required");
    expect(() => app.open()).toThrow("Organizer authorization required");
    const open = checking();
    const n = open.dispute(alice).result;
    open.as({ organizerSecret: alice });
    expect(() => open.resolve(n)).toThrow("Organizer authorization required");
    expect(() => open.close()).toThrow("Organizer authorization required");
  });

  it("rejects duplicate employee registration, across and within batches", () => {
    const app = setup();
    app.register(alice);
    expect(() => app.register(alice)).toThrow("Employee already registered");
    expect(() => app.register(bea, bea)).toThrow("Employee already registered");
  });

  it("registers a whole batch in one transaction and skips empty slots", () => {
    const app = setup();
    app.register(alice, bea, bytes(12), bytes(13));
    expect(app.state.registered.size()).toBe(4n);
    expect(app.state.registered.member(new Uint8Array(32))).toBe(false);
  });
});

describe("lifecycle", () => {
  it("starts committing and refuses disputes, closing or proving there", () => {
    const app = setup();
    expect(app.state.phase).toBe(Phase.committing);
    expect(() => app.open()).toThrow("Commit at least one category first");
    app.register(alice);
    app.commit();
    expect(() => app.dispute(alice)).toThrow("Disputes are only accepted while employees check");
    expect(() => app.close()).toThrow("The check window is not open");
    expect(() => app.publish()).toThrow("Close the check window before proving");
  });

  it("closes registration once employees start checking", () => {
    const app = checking();
    expect(() => app.register(mallory)).toThrow("Employee registration is closed");
    expect(() => app.open()).toThrow("already opened");
  });

  it("freezes the payroll and disputes once proving starts", () => {
    const app = checking();
    app.close();
    expect(() => app.commit()).toThrow("Payroll is frozen for proving");
    expect(() => app.dispute(alice)).toThrow("Disputes are only accepted while employees check");
    expect(() => app.close()).toThrow("The check window is not open");
  });
});

describe("employee self-check", () => {
  it("recomputes the committed root from one record and its path", () => {
    for (const slot of [0, 5, 12, 15]) {
      const proof = inclusionProof(engineering.records, slot);
      expect(rootFromRecord(engineering.records[slot], proof)).toBe(engineering.root);
    }
  });

  it("detects a record that is not the one committed", () => {
    const proof = inclusionProof(engineering.records, 3);
    const wrong = { ...engineering.records[3], pay: engineering.records[3].pay - 100n };
    expect(rootFromRecord(wrong, proof)).not.toBe(engineering.root);
  });

  it("salts every record so equal pay never produces equal leaves", () => {
    const a = buildCategory("A", people([3000], [3000]));
    expect(toHex(pureCircuits.recordLeaf(a.records[0]))).not.toBe(toHex(pureCircuits.recordLeaf({ ...a.records[0], salt: bytes(9) })));
    expect(a.root).not.toBe(buildCategory("A", people([3000], [3000])).root);
  });
});
